export const LOGIN = "LOGIN";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";


export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const GET_USER = "GET_USER";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";


export const ADD_USER = "ADD_USER";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";


export const EDIT_COMPTE = "EDIT_COMPTE";
export const EDIT_COMPTE_FAIL = "EDIT_COMPTE_FAIL";
export const EDIT_COMPTE_SUCCESS = "EDIT_COMPTE_SUCCESS";

export const DELETE_COMPTE = "DELETE_COMPTE";
export const DELETE_COMPTE_FAIL = "DELETE_COMPTE_FAIL";
export const DELETE_COMPTE_SUCCESS = "DELETE_COMPTE_SUCCESS";



export const ADD_COMPTE = "ADD_COMPTE";
export const ADD_COMPTE_FAIL = "ADD_COMPTE_FAIL";
export const ADD_COMPTE_SUCCESS = "ADD_COMPTE_SUCCESS";

export const GET_COMPTE = "GET_COMPTE";
export const GET_COMPTE_FAIL = "GET_COMPTE_FAIL";
export const GET_COMPTE_SUCCESS = "GET_COMPTE_SUCCESS";